# Streamware Podman Compose Configuration
# Rootless container support with Podman
# Usage: podman-compose up -d

version: '3.8'

networks:
  streamware-net:
    driver: bridge

volumes:
  ollama_data:
  redis_data:
  qdrant_data:
  app_data:

services:
  backend:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.backend
    container_name: streamware-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - STREAMWARE_ENV=production
      - DATABASE_URL=sqlite:///data/streamware.db
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - app_data:/app/data
      - ../../apps:/app/apps:ro
    networks:
      - streamware-net
    security_opt:
      - label=disable
    userns_mode: keep-id

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: streamware-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - streamware-net
    security_opt:
      - label=disable

  redis:
    image: docker.io/redis:alpine
    container_name: streamware-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - streamware-net
